### ISSUE TITLE
even xdescribe() functions get their string printed on browser

### ISSUE THREAD

**Issue by tripti825** [dfederm/karma-jasmine-html-reporter#13]
Even after putting an x on a describe() function, it prints its string on browser, though on console it skips it, i.e. overall it skips the test but still prints the string on browser. Shouldn't this be avoided? Confuses users, specially first time, on whether the test is actually being skipped or not.

**Comment by dfederm** [comment]
Can you elaborate on what you mean by "printed in the browser"? Do you mean printed in the console?

Can you show what you're talking about vis a screen snippet?

**Comment by dfederm** [comment]
Closing due to lack of detail and followup
