### ISSUE TITLE
[error] Uncaught TypeError: env.configure is not a function 

### ISSUE THREAD

**Issue by lcervo** [dfederm/karma-jasmine-html-reporter#18]
I am experiencing a massive problem when running my tests. 2 days ago they were running fine but today I get:

**Uncaught TypeError: env.configure is not a function** 

in the file: [...]/node_modules/karma-jasmine-html-reporter/src/lib/adapter.js

````
[...]
 config.specFilter = function (spec) {
    return specFilter.matches(spec.getFullName());
  };

  env.configure(config); <--- _the error is thrown here_

  htmlReporter.initialize();
[...]
````

We are using a .net core angular 6 application.

this is my package.json:

dependencies": {
    "@angular/animations": "6.1.10",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/compiler-cli": "6.1.10",
    "@angular/core": "6.1.10",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "6.1.10",
    "@angular/http": "6.1.10",
    "@angular/platform-browser": "6.1.10",
    "@angular/platform-browser-dynamic": "6.1.10",
    "@angular/platform-server": "6.1.10",
    "@angular/router": "6.1.10",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "@ngrx/effects": "^6.1.0",
    "@ngrx/entity": "^6.1.0",
    "@ngrx/router-store": "^6.1.0",
    "@ngrx/store": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "@progress/kendo-angular-buttons": "^4.1.3",
    "@progress/kendo-angular-dateinputs": "^3.4.4",
    "@progress/kendo-angular-dialog": "^3.7.0",
    "@progress/kendo-angular-dropdowns": "^3.0.3",
    "@progress/kendo-angular-excel-export": "^2.1.2",
    "@progress/kendo-angular-grid": "^3.6.1",
    "@progress/kendo-angular-inputs": "^3.2.1",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.1.0",
    "@progress/kendo-angular-popup": "^2.4.2",
    "@progress/kendo-angular-tooltip": "^1.0.0",
    "@progress/kendo-data-query": "^1.5.0",
    "@progress/kendo-drawing": "^1.5.7",
    "@progress/kendo-file-saver": "^1.0.7",
    "@progress/kendo-theme-bootstrap": "^2.13.8",
    "@progress/kendo-theme-default": "latest",
    "@types/lodash": "^4.14.116",
    "angular-router-loader": "^0.8.5",
    "codelyzer": "^4.4.4",
    "css": "2.2.4",
    "css-loader": "1.0.0",
    "es6-shim": "0.35.3",
    "expose-loader": "0.7.5",
    "file-loader": "2.0.0",
    "font-awesome": "^4.7.0",
    "html-loader": "0.5.5",
    "jasmine-marbles": "^0.4.0",
    "json-loader": "0.5.7",
    "lodash": "^4.17.11",
    "ng-bootstrap": "^1.6.3",
    "node-sass": "^4.9.3",
    "normalize.css": "^8.0.0",
    "oidc-client": "^1.5.3-beta.1",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "rxjs": "^6.3.2",
    "rxjs-compat": "^6.0.0",
    "sass-loader": "^7.1.0",
    "style-loader": "0.23.1",
    "to-string-loader": "1.1.5",
    "url-loader": "1.1.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.2",
    "@angular/cli": "6.2.4",
    "@ngrx/schematics": "^6.1.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@types/chai": "4.1.6",
    "@types/jasmine": "2.8.9",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^10.10.0",
    "chai": "4.2.0",
    "jasmine-core": "3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "3.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.3",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-teamcity-reporter": "^1.1.0",
    "karma-webpack": "3.0.5",
    "ngrx-store-freeze": "^0.2.4",
    "rimraf": "^2.6.2",
    "ts-node": "~7.0.1",
    "tslint": "^5.11.0",
    "typescript": "^2.9.2"
  }

**Comment by dfederm** [comment]
You'll either need to upgrade to Jasmine 3.3, or downgrade this package to 1.3.1.

You're not the first to run into this, so a bit later I will update the readme with a version compatible chart.

**Comment by trickeyone** [comment]
I'm getting this error, too. I'm on jasmine@^3.3.1
