### ISSUE TITLE
[error]: If `seed` is a function the report building raises an error

### ISSUE THREAD

**Issue by ander2** [dfederm/karma-jasmine-html-reporter#19]
I configured the seed parameter as a function (`Math.floor(Math.random()*10000)`) and when all tests pass and the reporter tries to write the report, the following error is raised:

``` 
{ 
"message": "An error was thrown in afterAll\nTypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at <Jasmine>
    at createDom (node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:479:16)
    at HtmlReporter.jasmineDone (node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:216:11)
    at <Jasmine>
    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/zone-testing.js?:613:42)
    at <Jasmine>",
"str": "An error was thrown in afterAll TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at <Jasmine>\n    at createDom (node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:479:16)
    at HtmlReporter.jasmineDone (node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:216:11)
    at <Jasmine>\n    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/zone-testing.js?:613:42)
    at <Jasmine>" Chrome 70.0.3538 (Mac OS X 10.14.0): Executed 32 of 727 (skipped 695) ERROR (37.501 secs / 36.03 secs)
```

As it's not specified anywhere, I don't know if using a function for the seed is supported or if this is a bug. 
Any clarification would be appreciated.

**Comment by dfederm** [comment]
> I configured the seed parameter as a function (`Math.floor(Math.random()*10000)`)

Can you elaborate on what you mean by this?

**Comment by ander2** [comment]
Sorry If that wasn't clean. I mean, I configured the `client` section on `karma.conf.js` like this:
```js
client:{
      clearContext: false, // leave Jasmine Spec Runner output visible in browser
      jasmine: {
        random: true,
        seed: Math.floor(Math.random()*10000),
        oneFailurePerSpec: true,
        failFast: true,
        timeoutInterval: 9000
      }
    },
```

**Comment by britvik** [comment]
It crashes when you set seed as a number. String works OK.

@dfederm could you handle this case by changing following line:
`if (typeof child === 'string') {`
to:
`if (typeof child === 'string' || typeof child === 'number') {`
in createDom function? Since child here is the seed we set in the config and it goes to else branch and crashes with Error message stated above.

Funny note: [jasmine docs](https://jasmine.github.io/api/3.3/Configuration.html) say that seed should be a function, but it works with number or string but not a function :).

**Comment by ander2** [comment]
After @britvik 's response I've checked jasmines source code and it's clear that the `seed` must be a function that returns a different value for each run. 

Related to this issue, `karma-jasmine`'s docs should also be updated as they show `seed` as an string in their [examples](https://github.com/karma-runner/karma-jasmine).

**Comment by britvik** [comment]
I'm not sure which source you checked @ander2 , but the  [source](https://github.com/jasmine/jasmine/blob/110c092c9ece00cd6c882bd573b911c35ff73478/src/core/Order.js) I found, uses seed as a value (string or number). So it seems they only forgot to update the docs.

By the way, why did you try to randomize the seed? It's randomized by default. They use `String(Math.random()).slice(-5)` internally.

Conclusion:
Just use string as a seed :). Although `karma-jasmine-html-reporter` should be fixed to not crash when you use a number.

**Comment by crfrolik** [comment]
> Although karma-jasmine-html-reporter should be fixed to not crash when you use a number.

Can this issue be re-opened to fix this? I just got burned by it.

```
Chrome 86.0.4240.198 (Windows 10) ERROR
  An error was thrown in afterAll
  TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
      at createDom (node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:660:16)
      at HtmlReporter.jasmineDone (node_modules/karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js:257:11)
      at <Jasmine>
```

**Comment by helight59** [comment]
same problem.
Error with 
```
const a = document.createElement('a');
document.body.appendChild(a);
```

**Comment by helight59** [comment]
@crfrolik check object, where should be Node. Console mb. You need mock method `appendChild` like:
`spyOn(document.body, 'appendChild').and.returnValue(spyObject);`
