### ISSUE TITLE
Large content is not scrollable

### ISSUE THREAD

**Issue by Mokkapps** [dfederm/karma-jasmine-html-reporter#21]
Hi,

I am using latest version 1.4.0 with these devDependencies in an Angular application but the content cannot be scrolled horizontally so I cannot see the whole error message:

```json
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.13.1",
        "@angular/cli": "7.3.1",
        "@angular/compiler-cli": "^7.2.5",
        "@angular/language-service": "^7.2.5",
        "@types/csvtojson": "^1.1.5",
        "@types/jasmine": "^3.3.9",
        "@types/jasmine-expect": "^3.8.1",
        "@types/jasminewd2": "~2.0.6",
        "@types/node": "^11.9.4",
        "codelyzer": "^4.5.0",
        "https-proxy-agent": "^2.2.1",
        "is-docker": "^1.1.0",
        "jasmine-auto-spies": "^3.2.1",
        "jasmine-core": "^3.3.0",
        "jasmine-expect": "^4.0.1",
        "jasmine-marbles": "^0.4.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-cli": "~2.0.0",
        "karma-coverage-istanbul-reporter": "^2.0.5",
        "karma-jasmine": "^2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "karma-jasmine-matchers": "^4.0.1",
        "karma-junit-reporter": "^1.2.0",
        "ng-mocks": "^7.5.0",
        "node-sass": "^4.11.0",
        "prettier": "^1.16.4",
        "ts-node": "~8.0.2",
        "tslint": "~5.12.1",
        "typescript": "3.2.4"
    }
```
Tests are running in Chrome Version 72.0.3626.119 (Official Build) (64-bit)

![capture](https://user-images.githubusercontent.com/3127210/53482163-e8f26200-3a7e-11e9-9298-897b5ce639e6.PNG)

**Comment by mrnocreativity** [comment]
Seeing the same issue. I have many tests which causes a vertical overflow in the speclist. I can't scroll the page to view anything beneath the fold.

A quick check in the kjhtml browser window shows a few CSS properties set to the body of the context.html which sets the body to 'position: fixed'. This causes the problem. 

I'm not sure where in the code this is being added. Could be a Jasmine/Karma thing actually.
If anybody figures out where this should be changed, let's make a pull request. This shouldn't be too hard to fix :)

**Comment by dfederm** [comment]
As this package just re-packages parts of Jasmine, you can find the css here:
https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.css

If a fix is made there and they release it, I can refresh this package as well.
