### ISSUE TITLE
Support for markdown

### ISSUE THREAD

**Issue by Akxe** [dfederm/karma-jasmine-html-reporter#22]
It would be awesome if you could write markdown in the `it` and `describe`.

Thinks like <pre><code>it('should change from invalid initial value', () => { });
it('should **not** change from valid initial value', () => { });
</code></pre>

**Comment by Akxe** [comment]
@dfederm Why, was this closed? Please add small summary.

**Comment by dfederm** [comment]
This package is pretty much just a copy of Jasmine's html reporter. Any changes should be done in Jasmine and then they can be copied here.

See: https://github.com/dfederm/karma-jasmine-html-reporter/blob/master/README.md#develop
