### ISSUE TITLE
[error] Errors spill off the sides of the browser window on test failure in angular

### ISSUE THREAD

**Issue by pixelpax** [dfederm/karma-jasmine-html-reporter#27]
"@angular/core": "7.2.0"
    "jasmine-core": "~2.8.0",
    "jasmine-fail-fast": "^2.0.0",
    "jasmine-reporters": "^2.3.2",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0"

I'm seeing test failures falling off the page. Somehow the element with class .html-reporter is expanding beyond the width of the page. This is fixed by adding `width: 100%` to the class `.html-reporter`

![image](https://user-images.githubusercontent.com/1467013/58046782-e9dde180-7b0b-11e9-9020-13a12a576cd6.png)

**Comment by pixelpax** [comment]
https://github.com/dfederm/karma-jasmine-html-reporter/pull/28

**Comment by dfederm** [comment]
This file is basically just a copy of this one:
https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.css

So I think any fixes should go there and then I'll copy it over.

**Comment by pixelpax** [comment]
OK! https://github.com/jasmine/jasmine/pull/1713

**Comment by dfederm** [comment]
Closing as the change has been made in Jasmine and pulled into this package.
