### ISSUE TITLE
Fail if DOM is overwritten

### ISSUE THREAD

**Issue by johnjbarton** [dfederm/karma-jasmine-html-reporter#30]
If a test mutates the DOM say to add HTML for a test, then we can reach this code and not have the banner or alert:
```
this.jasmineDone = function (doneResult) {
      var banner = find('.jasmine-banner');
      var alert = find('.jasmine-alert');
...
```

We added
```js
    if (typeof banner === 'undefined' || typeof alter === 'undefined') {
        console.warn('Cannot report final jasmine results to browser, DOM was overwritten');
        return this;
     }
```
to work around this issue.

**Comment by dfederm** [comment]
As per the [readme](https://github.com/dfederm/karma-jasmine-html-reporter#develop), this package's code is pretty much copied from jasmine itself. Please make the fix there and then once jasmine ships with the change, we can pull it in here.
