### ISSUE TITLE
Warning spam if DOM has been overwritten

### ISSUE THREAD

**Issue by jaylynch** [dfederm/karma-jasmine-html-reporter#34]
Similar to #30 if the DOM has been overwritten, warnings are issued when the `symbols` div is not found, often leading to huge volumes of spam in the output.

Occurs at `html.jasmine.reporter.js:157`

**Comment by dfederm** [comment]
As per the [readme](https://github.com/dfederm/karma-jasmine-html-reporter#develop), this package's code is pretty much copied from jasmine itself. Please make the fix there and then once jasmine ships with the change, we can pull it in here.
