### ISSUE TITLE
Selecting one spec is not possible with  karma-jasmine 3.1

### ISSUE THREAD

**Issue by HolgerJeromin** [dfederm/karma-jasmine-html-reporter#39]
The link generated by this html-reporter does not work anymore. We get a white background without any content.

This is already reported over there: https://github.com/karma-runner/karma-jasmine/issues/256
Probably [this change ](https://github.com/karma-runner/karma-jasmine/pull/243) causes the failure. At least the newline in `getSpecsByName` throws the error that is shown in the console...

````
Uncaught Error: No spec found with name: "mySpec"
    at getSpecsByName (adapter.js:346)
    at getDebugSpecToRun (adapter.js:356)
    at getSpecsToRun (adapter.js:431)
    at new KarmaSpecFilter (adapter.js:437)
    at createSpecFilter (adapter.js:454)
    at ContextKarma.start (adapter.js:481)
    at ContextKarma.window.__karma__.loaded (debug.js:27)
    at debug.html?spec=mySpec:1353
````

**Comment by dfederm** [comment]
Thanks, following up on the karma-jasmine issue since I believe the issue is on that side.

**Comment by HolgerJeromin** [comment]
Fixed with https://github.com/karma-runner/karma-jasmine/pull/270
Tested with "karma-jasmine": "3.3.1"
