### ISSUE TITLE
Display warnings

### ISSUE THREAD

**Issue by jchapelle** [dfederm/karma-jasmine-html-reporter#42]
Whould it be possible to display warnings message and their source component ?

**Comment by dfederm** [comment]
Can you clarify?

Also, per the readme:

> adapter.js, html.jasmine.reporter.js, and jasmine.css are copied with small adjustments from jasmine/lib/jasmine-core/boot.js and jasmine/lib/jasmine-core/jasmine-html.js, and jasmine/lib/jasmine-core/jasmine.css respectively.

So most changes should be made in the appropriate repos and then they'll make there way to this one.
