### ISSUE TITLE
How to save the report as files?

### ISSUE THREAD

**Issue by lamba92** [dfederm/karma-jasmine-html-reporter#43]
I found no way to save the report in a folder. Is that intended or am I missing something? I need to store the report for CI testing for later display.

**Comment by dfederm** [comment]
No, it does not have the option to save to a folder.

**Comment by lamba92** [comment]
Is there any particular reason or just not implemented? I am new to JS frontend world and coming from Gradle build scan I am kind of lost ^^

**Comment by dfederm** [comment]
It's just not implemented, but I also think it would be pretty difficult to implement based on how it works. It basically hooks the jasmine html reporter into the karma debug page.

**Comment by dfederm** [comment]
I'd recommend something like [karma-junit-reporter](https://www.npmjs.com/package/karma-junit-reporter) for saving results to a file which can then be later visualized.
