### ISSUE TITLE
Need to scroll past 280 Tests to see the loaded component

### ISSUE THREAD

**Issue by Jeremias-Nater** [dfederm/karma-jasmine-html-reporter#47]
I am using this reporter with Angular (by default). My suggestion to improve this would be an option to also hide all non-executed tests, so that i can focus my new test with "fdescribe" and only see the focused test result above the component. Another way to solve this would be an option to display the results below the tested component.

hideDisabled does not seem to achieve this

**Comment by dfederm** [comment]
As per the [Develop](https://github.com/dfederm/karma-jasmine-html-reporter#develop) section in the readme:

> There's not much to this package.
> 
> adapter.js, html.jasmine.reporter.js, and jasmine.css are copied with small adjustments from jasmine/lib/jasmine-core/boot.js and jasmine/lib/jasmine-core/jasmine-html.js, and jasmine/lib/jasmine-core/jasmine.css respectively.
> 
> Just pull over changes from Jasmine as needed. There is a script to help with that; just run npm run build and review the changes. Specifically, adapter.js needs a lot of manual removals.

So most proposed changes should actually be made in Jasmine.

**Comment by dfederm** [comment]
Try this option:

![image](https://user-images.githubusercontent.com/6445614/125144475-dff40f80-e0d2-11eb-828d-e0bb63baf9fa.png)

Seems to work for me.
