### ISSUE TITLE
CSS rule causes overlap

### ISSUE THREAD

**Issue by Jeremias-Nater** [dfederm/karma-jasmine-html-reporter#48]
![image](https://user-images.githubusercontent.com/8191311/110621988-2d9b5280-819b-11eb-8bde-52b3e8d06561.png)

**The overlap is caused by**

![image](https://user-images.githubusercontent.com/8191311/110621922-19efec00-819b-11eb-939e-68e4ba072653.png)

**Comment by dfederm** [comment]
As per the [Develop](https://github.com/dfederm/karma-jasmine-html-reporter#develop) section in the readme:

> There's not much to this package.
> 
> adapter.js, html.jasmine.reporter.js, and jasmine.css are copied with small adjustments from jasmine/lib/jasmine-core/boot.js and jasmine/lib/jasmine-core/jasmine-html.js, and jasmine/lib/jasmine-core/jasmine.css respectively.
> 
> Just pull over changes from Jasmine as needed. There is a script to help with that; just run npm run build and review the changes. Specifically, adapter.js needs a lot of manual removals.

So most proposed changes should actually be made in Jasmine.
