### ISSUE TITLE
Add option to suppress skipped tests

### ISSUE THREAD

**Issue by arobinson** [dfederm/karma-jasmine-html-reporter#51]
When using `fit` to test one test, this reporter still prints out all the "dots" for the tests that aren't run. This really slows down the tests especially when debugging one test. Please add an option to not include the dots for skipped tests.

![image](https://user-images.githubusercontent.com/93213/122443017-65fdba00-cf5c-11eb-9389-e9e9738ee10b.png)

**Comment by dfederm** [comment]
This option already exists:

![image](https://user-images.githubusercontent.com/6445614/125144463-d2d72080-e0d2-11eb-9f2c-b46f9cbbc94a.png)

**Comment by arobinson** [comment]
Is there a reporter config to set this? (Not something to toggle in the UI that has to be set each time)
