### ISSUE TITLE
Tests are not sorted

### ISSUE THREAD

**Issue by fingerartur** [dfederm/karma-jasmine-html-reporter#52]
Test results (dots and crosses) are sorted randomly each time you run your suite, which can be confusing

**Comment by fingerartur** [comment]
Fix is here https://github.com/dfederm/karma-jasmine-html-reporter/pull/53

**Comment by fingerartur** [comment]
In the meantime you can install from my fork 
```
npm i -D git+https://github.com/fingerartur/karma-jasmine-html-reporter.git
yarn add -D git+https://github.com/fingerartur/karma-jasmine-html-reporter.git
```

**Comment by dfederm** [comment]
This is by design and recommended to ensure tests are isolated.

You can disable this behavior via this option:

![image](https://user-images.githubusercontent.com/6445614/125144647-5a249400-e0d3-11eb-8368-b6681ac166ae.png)
