### ISSUE TITLE
Changing the lower bounds of a peer dependency is a breaking change.

### ISSUE THREAD

**Issue by alan-agius4** [dfederm/karma-jasmine-html-reporter#54]
In version 1.7.0, the minimum supported version of jasmine-core was bumped from 3.7 to 3.8.

Removing the lower bounds of a peerDependency is technically a breaking change and should be considered as such and therefore be released a major versions especially considering the restrictions on peerDependency when using NPM 7.

**Comment by dfederm** [comment]
https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by alan-agius4** [comment]
A peer dependency is not a dependency of your project and therefore it should be threaded differently.

This is also the consensus with the maintainers of semver https://github.com/semver/semver/issues/502

**Comment by alan-agius4** [comment]
A peer dependency is not a dependency of your project and therefore it should be treated differently.

A peer dependency version, should be treated as part of the public API.

This is also the consensus with the maintainers of semver https://github.com/semver/semver/issues/502

**Comment by dfederm** [comment]
Ack

I'm not really seeing where this is a problem in practice though. If you allow minor version updates, then karma and this package will update together. If you don't, then neither will upgrade. If you explicitly try to update this package, you get an error which explains that you need up update both. So I don't see a (reasonable) scenario where this is a problem.

Finally, this is the versioning strategy this package has always used and this has never come up as an issue before. Why now?

**Comment by alan-agius4** [comment]
Actually we did notice the same issue before, I think it was in 1.5.0. Now, with NPM 7 NPM peer dependencies are stricter, meaning that unmet peer dependencies will cause npm install to fail.

Agreed that if you consumer of this library used the same semver strategy example both for jasmine-core and karma-jasmine-html-reporter. Either both pinned, both with tilde or both with a caret. This shouldn’t be a problem.

**Comment by dfederm** [comment]
Sounds good. I'll leave the current state as-is instead of unpublishing and republishing (barring and substantial real world issues that pop up in the next week or so), and going fwd I'll follow the semver guidance more closely and bump the major when updating peer deps.
