### ISSUE TITLE
Can we have a way to hide excluded tests from test result summary?

### ISSUE THREAD

**Issue by Jamie5** [dfederm/karma-jasmine-html-reporter#56]
This would especially be useful in cases of using fit/fdescribe.

Essentially, the desire would be to, in https://github.com/dfederm/karma-jasmine-html-reporter/blob/main/src/lib/html.jasmine.reporter.js , have another condition in `if (filterSpecs && !hasActiveSpec(resultNode)) {` which would be a flag we set in the config.

**Comment by dfederm** [comment]
As per the readme:

> adapter.js, html.jasmine.reporter.js, and jasmine.css are copied with small adjustments from jasmine/lib/jasmine-core/boot.js and jasmine/lib/jasmine-core/jasmine-html.js, and jasmine/lib/jasmine-core/jasmine.css respectively.

Do this request should be made in the jasmine repo.

**Comment by Jamie5** [comment]
Thank you, I will check there.

**Comment by jdugas** [comment]
@Jamie5 
Did you find a way to do that?

**Comment by jdugas** [comment]
I figured it out.
I had to set it in the karma.config.js file.

```
module.exports = function (config) {
  config.set({
    ],
    client: {
      jasmine: {
        // you can add configuration options for Jasmine here
        // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
        hideDisabled: true,
      },
    },
...
```
