### ISSUE TITLE
Currently works only with Jasmine 3, not with Jasmine 4

### ISSUE THREAD

**Issue by Cito** [dfederm/karma-jasmine-html-reporter#68]
Jasmine 4 was released in Feb 2022 and it contains some breaking changes causing incompatibility with the current version 1.7.0 of karma-jasmine-html-reporter which was released in Jul 2021.

Particularly, there are [changes in how Jasmine is configured](https://github.com/jasmine/jasmine/blob/main/release_notes/4.0.0.md#changes-to-how-jasmine-is-configured). While Jasmine 3 used `failFast` and `oneFailurePerSpec`, Jasmine 4 uses `stopOnSpecFailure` and `stopSpecOnExpectationFailure`, and karma-jasmine-html-reporter does not support these.

Unfortunately, the README page does not specify that it breaks with Jasmine 4, and the requirements also has peerDepencency Jasmine >=3.8, therefore it took me quite a while to find that it is actually not compatible.

**Comment by dfederm** [comment]
Thanks for reporting, I'll rev the version later today

**Comment by dfederm** [comment]
Quick update, I decided to rewrite this so I don't have to rev the version and it just uses whatever version of jasmine you actually have as a dependency. I'm running into an issue though so it's taking a little longer than I thought.

Branch "v2" has the changes if anyone cares to try to debug (run `npm test`)

**Comment by dfederm** [comment]
Fixed in v2.0.0

**Comment by Cito** [comment]
Seems to work now. Thank you for the quick fix @dfederm!
