### ISSUE TITLE
Specs not nesting under describes

### ISSUE THREAD

**Issue by cgs-lbergeron** [dfederm/karma-jasmine-html-reporter#69]
![karma](https://user-images.githubusercontent.com/90052629/178361926-886cce57-6fa4-4858-b193-42c8c9fde594.png)

**Comment by dfederm** [comment]
@cgs-lbergeron  Please provide repro steps.

**Comment by cgs-lbergeron** [comment]
> @cgs-lbergeron Please provide repro steps.

Not sure as the project has always been like that since I started working on it. I start karma using the angular cli 'ng test', I attached the karma.conf file. 
[karma.conf.txt](https://github.com/dfederm/karma-jasmine-html-reporter/files/9087771/karma.conf.txt)

**Comment by dfederm** [comment]
@cgs-lbergeron I'm not able to repro, so you'll need to provide more information.

**Comment by cgs-lbergeron** [comment]
@dfederm Sadly I won't be able to provide much more info, so I guess this can be closed.

**Comment by cgs-lbergeron** [comment]
@dfederm Actually I just found the issue and for your information it was caused by a global scss rule. Sorry about that.
