### ISSUE TITLE
Support Jasmine 5

### ISSUE THREAD

**Issue by Yberion** [dfederm/karma-jasmine-html-reporter#74]
Hello @dfederm,

Do you think it would be possible to support Jasmine 5 ?

I don't know if bumping the version to `"jasmine-core": "^4.0.0 | ^5.0.0"` would be enough.
I think it would require an updated version of `karma-jasmine` as well, I've made a ticket for that https://github.com/karma-runner/karma-jasmine/issues/333.

Have a good day.

**Comment by dfederm** [comment]
This is done as of 2.1.0.

Note that because `karma-jasmine` still depends on `jasmine-core ^4.1.0`, you may also need this in your `package.json`:

```json
  "overrides": {
    "karma-jasmine": {
      "jasmine-core": "^4.1.0 || ^5.0.0"
    }
  }
```

At least I did.
