### ISSUE TITLE
debug.html showing Jasmine errors, but all tests passed.

### ISSUE THREAD

**Issue by dailytabs** [dfederm/karma-jasmine-html-reporter#78]
All tests pass, but the `debug.html` page loads to the "Failures" tab and shows the following:

![image](https://github.com/user-attachments/assets/3be92de7-01dd-4fe7-8fc7-9204fc335a4d)

Since my code is listed no where in the stack traces, I have no recourse but to report as a bug.

**Comment by dfederm** [comment]
Please provide detailed repro steps. The screens screenshot alone is not actionable. 

Note that the debug page simply runs your UTs in that page itself, so this is not likely to be a bug in karma-jasmine-html-reporter

**Comment by dailytabs** [comment]
Yes, sorry. This had to do with differences between how spying on `sessonStorage` works across browsers.
