### ISSUE TITLE
Fix result-message div content too large for the parent 

### ISSUE THREAD

**Issue by ybarbaria** [dfederm/karma-jasmine-html-reporter#8]
https://github.com/dfederm/karma-jasmine-html-reporter/blob/6c12b7d7a43e85f7b72304046656bfc96e9c8890/src/css/jasmine.css#L57

Hello,

Can I began contributor? I would like to help with this feature. 

I have updated the jasmine.css file like that :
.html-reporter .result-message { padding-top: 14px; color: #333333; white-space: pre; overflow: auto } .html-reporter .result-message span.result { display: block; }

I saw one error on design after using your reporter :

![36252009-9047c9f6-1243-11e8-806e-a24eaa72fc52](https://user-images.githubusercontent.com/5574663/38925609-6c22b142-4300-11e8-88b3-105e6e6aa775.png)

The error come from your css :
html-reporter .result-message { padding-top: 14px; color: #333333; white-space: pre; }

Fix :
You fix it by adding overflow: auto. in this case a scrollbar will appear.
Or replace white-space:pre by white-space: pre-wrap;, in this case the content will be wrapped.

![36252176-ff6bfd70-1243-11e8-97c0-81faae519bbe](https://user-images.githubusercontent.com/5574663/38925622-71f18bf2-4300-11e8-84a9-a27ae497851c.png)

Thx :)

**Comment by dfederm** [comment]
This file is basically just a copy of this one:
https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.css

So I think any fixes should go there and then I'll copy it over.

**Comment by dfederm** [comment]
This should be fixed in 1.3.0, which includes [this change](https://github.com/jasmine/jasmine/commit/e2d9eefccdca3916b341a4927de7919003525cbc#diff-bed4c8c3ac8b74b561200de4a29100dd) from Jasmine.
